import getTokens from '@kiwicom/orbit-components/lib/getTokens';

const customTokens = getTokens({
  palette: {
    product: {
      light: '#F2FAFF',
      normal: '#00AFF2',
      dark: '#0094CC',
      darker: '#0078A6',
      lightHover: '#DCEDF7',
      normalHover: '#00A4E3',
      darkHover: '#0088BD',
      lightActive: '#C7E1F0',
      normalActive: '#0099D4',
      darkActive: '#0081B2',
    },
    blue: {
      light: '#F2FAFF',
      normal: '#00AFF2',
      dark: '#0094CC',
      darker: '#0078A6',
      lightHover: '#DCEDF7',
      normalHover: '#00A4E3',
      darkHover: '#0088BD',
      lightActive: '#C7E1F0',
      normalActive: '#0099D4',
      darkActive: '#0081B2',
    },
    white: {
      normal: '#FFFFFF',
      normalHover: '#F5F7F9',
      normalActive: '#E5EAEF',
    },
    cloud: {
      light: '#F5F7F9',
      normal: '#EFF2F5',
      dark: '#E8EDF1',
      lightHover: '#E5EAEF',
      normalHover: '#DCE3E9',
      darkerHover: '#A6B6C8',
      lightActive: '#D6DEE6',
      normalActive: '#CAD4DE',
      darkerActive: '#94A8BE',
    },
    ink: {
      lighter: '#697D95',
      light: '#4F5E71',
      normal: '#252A31',
    },
    green: {
      light: '#EBF4EC',
      normal: '#28A138',
      dark: '#2B7336',
      darker: '#1D4D24',
      lightHover: '#D7EAD9',
      normalHover: '#238B31',
      darkHover: '#25632F',
      lightActive: '#C3DFC7',
      normalActive: '#1D7228',
    },
    orange: {
      light: '#FDF0E3',
      normal: '#E98305',
      dark: '#AE5700',
      darker: '#874400',
      lightHover: '#FAE2C7',
      normalHover: '#DC7C05',
      darkHover: '#8F4700',
      lightActive: '#F8D3AB',
      normalActive: '#CD7304',
      darkActive: '#753A00',
    },
    red: {
      light: '#FAEAEA',
      normal: '#D21C1C',
      dark: '#970C0C',
      darker: '#700909',
      lightHover: '#F4D2D2',
      normalHover: '#B91919',
      darkHover: '#890B0B',
      lightActive: '#EEB9B9',
      normalActive: '#9D1515',
      darkActive: '#9D1515',
    },
  },
  base: {
    fontFamily: `"Circular Pro", -apple-system, ".SFNSText-Regular", "San Francisco",
    "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;`,
  },
});

export default customTokens;
